name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.0

    - name: Install asdf plugins
      run: |
        asdf plugin add python
        asdf plugin add poetry

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ~/.asdf
        key: v4-${{ runner.os }}-asdf-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          v4-${{ runner.os }}-asdf-

    - name: Install tools
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        asdf install

    - name: Install deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      # pip 20.1 fails on generation of multiple .egg-info dirs
      run: |
        poetry config virtualenvs.create false
        poetry run pip install pip==20.0.2
        poetry run pip install -U setuptools
        poetry install --no-root

    - name: Build
      run: |
        poetry run python buildpre.py
        poetry install

    - name: Format
      run: |
        poetry run isort -y -c
        poetry run black --check .

  linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6.12, 3.7.9, 3.8.6, 3.9.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    # required for coverage
    - name: Install sqlite
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev

    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.0

    - name: Install asdf plugins
      run: |
        asdf plugin add python
        asdf plugin add poetry

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ~/.asdf
        key: v4-${{ runner.os }}-${{ matrix.python-version }}-asdf-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          v4-${{ runner.os }}-${{ matrix.python-version }}-asdf-

    - name: Install python
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        asdf install python ${{ matrix.python-version }}

    - name: Set python
      run: |
        asdf local python ${{ matrix.python-version }}

    - name: Install tools
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        asdf install

    - name: Install deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      # pip 20.1 fails on generation of multiple .egg-info dirs
      run: |
        poetry config virtualenvs.create false
        poetry run pip install pip==20.0.2
        poetry run pip install -U setuptools
        poetry install --no-root

    - name: Build
      run: |
        poetry run python buildpre.py
        poetry install

    - name: Test
      run: |
        poetry run pytest tests/

  macos:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6.12, 3.7.9, 3.8.6, 3.9.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.0

    - name: Install asdf plugins
      run: |
        asdf plugin add python
        asdf plugin add poetry

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ~/.asdf
        key: v4-${{ runner.os }}-${{ matrix.python-version }}-asdf-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          v4-${{ runner.os }}-${{ matrix.python-version }}-asdf-

    - name: Install python
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        asdf install python ${{ matrix.python-version }}

    - name: Set python
      run: |
        asdf local python ${{ matrix.python-version }}

    - name: Install tools
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        asdf install

    - name: Install deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      # pip 20.1 fails on generation of multiple .egg-info dirs
      run: |
        poetry config virtualenvs.create false
        poetry run pip install pip==20.0.2
        poetry run pip install -U setuptools
        poetry install --no-root

    - name: Build
      run: |
        poetry run python buildpre.py
        poetry install

    - name: Test
      run: |
        poetry run pytest tests/
