name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.1

    - name: Install asdf plugins
      run: |
        asdf plugin add python
        asdf plugin add poetry

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ~/.asdf
        key: v8-${{ runner.os }}-asdf-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          v8-${{ runner.os }}-asdf-

    - name: Install tools
      run: |
        asdf install
        poetry config virtualenvs.create false
        poetry run pip install -U pip setuptools wheel

    - name: Build
      run: |
        poetry run pip install cython oldest-supported-numpy
        poetry run python buildpre.py
        poetry run python build.py build_ext --inplace --force

    - name: Install deps
      run: |
        poetry install --no-root

    - name: Format
      run: |
        poetry run isort -y -c
        poetry run black --check .

  linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.12, 3.8.12, 3.9.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

      # sqlite for coverage
      # llvm for shap
    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev llvm

    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.1

    - name: Install asdf plugins
      run: |
        asdf plugin add python
        asdf plugin add poetry

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ~/.asdf
        key: v8-${{ runner.os }}-${{ matrix.python-version }}-asdf-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          v8-${{ runner.os }}-${{ matrix.python-version }}-asdf-

    - name: Install python
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        asdf install python ${{ matrix.python-version }}

    - name: Set python
      run: |
        asdf local python ${{ matrix.python-version }}

    - name: Install tools
      run: |
        asdf install
        poetry config virtualenvs.create false
        poetry run pip install -U pip setuptools wheel

    - name: Build
      run: |
        poetry run pip install cython oldest-supported-numpy
        poetry run python buildpre.py
        poetry run python build.py build_ext --inplace --force

    - name: Install deps
      run: |
        poetry install --no-root

    - name: Test
      run: |
        poetry run pytest tests/

  macos:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7.12, 3.8.12, 3.9.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

      # llvm for shap
    - name: Install system deps
      run: |
        brew update
        brew install llvm@9

    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.1

    - name: Install asdf plugins
      run: |
        asdf plugin add python
        asdf plugin add poetry

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ~/.asdf
        key: v8-${{ runner.os }}-${{ matrix.python-version }}-asdf-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          v8-${{ runner.os }}-${{ matrix.python-version }}-asdf-

    - name: Install python
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        asdf install python ${{ matrix.python-version }}

    - name: Set python
      run: |
        asdf local python ${{ matrix.python-version }}

    - name: Install tools
      run: |
        asdf install
        poetry config virtualenvs.create false
        poetry run pip install -U pip setuptools wheel

    - name: Build
      run: |
        poetry run pip install cython oldest-supported-numpy
        poetry run python buildpre.py
        poetry run python build.py build_ext --inplace --force

    - name: Install deps
      run: |
        poetry install --no-root

    - name: Test
      run: |
        poetry run pytest tests/
