name: build wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    name: build ${{ matrix.py }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        py: ["cp37-*", "cp38-*", "cp39-*", "cp310-*", ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: ${{ matrix.py }}
          CIBW_ARCHS: auto
          CIBW_ARCHS_LINUX: auto64
          CIBW_BEFORE_BUILD: python buildpre.py
          CIBW_TEST_COMMAND: python -c "import skranger; print(skranger.__version__); from skranger import ranger"
